@url = http://localhost:3000

###
GET {{url}}/categorias

###
POST {{url}}/usuario
Content-Type: application/json

{
    "nome":"Luiza",
    "email":"luh@teste.com",
    "senha":"12345"
}

###
# @name createLogin
POST {{url}}/login
Content-Type: application/json

{
    "email":"luh@teste.com",
    "senha":"12345"
}

###
@token = {{createLogin.response.body.token}}

###
@idUser = {{createLogin.response.body.authenticatedUser.id}}

###
GET {{url}}/usuario
Authorization: Bearer {{token}}

###
PUT {{url}}/usuario
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome":"Luiza Ferreira",
    "email":"luh@teste.com",
    "senha": "12345"
}

###
# @name createID
POST {{url}}/produto
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao":"Bombom 5",
    "quantidade_estoque":0,
    "valor":1000,
    "categoria_id": 2
}

###
# @name createID
POST {{url}}/produto
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao":"Bombom 4",
    "quantidade_estoque":0,
    "valor":1000,
    "categoria_id": 5
}

###
@idProduct = {{createID.response.body.id}}

###
GET {{url}}/produto
Authorization: Bearer {{token}}

###
GET {{url}}/produto
?categoria_id=2
&categoria_id=5
Authorization: Bearer {{token}}

###
PUT  {{url}}/produto/{{idProduct}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao":"Bombom 5",
    "quantidade_estoque":333,
    "valor":1000,
    "categoria_id": 4
}
