@url = http://localhost:3000

###
GET {{url}}/categoria

###
POST {{url}}/usuario
Content-Type: application/json

{
    "nome":"Luiza",
    "email":"luh@teste.com",
    "senha":"12345"
}

###
# @name createLogin
POST {{url}}/login
Content-Type: application/json

{
    "email":"luh@teste.com",
    "senha":"12345"
}

###
@token = {{createLogin.response.body.token}}

###
@idUser = {{createLogin.response.body.authenticatedUser.id}}

###
GET {{url}}/usuario
Authorization: Bearer {{token}}

###
PUT {{url}}/usuario
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome":"Luiza Ferreira",
    "email":"luh@teste.com",
    "senha": "12345"
}

###
# @name createID
POST {{url}}/produto
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao":"Bombom 5",
    "quantidade_estoque":0,
    "valor":1000,
    "categoria_id": 2
}

###
# @name createID
POST {{url}}/produto
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao":"Bombom 4",
    "quantidade_estoque":0,
    "valor":1000,
    "categoria_id": 5
}

###
@idProduct = {{createID.response.body.id}}

###
GET {{url}}/produto
Authorization: Bearer {{token}}

###
GET {{url}}/produto
?categoria_id=2
&categoria_id=5
Authorization: Bearer {{token}}

###
PUT  {{url}}/produto/{{idProduct}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao":"Bombom 5",
    "quantidade_estoque":333,
    "valor":1000,
    "categoria_id": 4
}


###
GET  {{url}}/pedido
?cliente_id=2
Authorization: Bearer {{token}}

###
# @name clientID
POST  {{url}}/cliente
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome":"Maria joaquina",
    "email":"maria@teste.com",
    "cpf":"23267892300"
}

###
# @name clientID
POST  {{url}}/cliente
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome":"Quero ver o cep",
    "email":"email@teste2.com",
    "cpf":"03267892330",
    "cep":"80050350"
}

###
@clientID = {{clientID.response.body.id}}

###
PUT  {{url}}/cliente/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome":"Quero ver o cep",
    "email":"govel43146@weirby.com",
    "cpf":"03267892300",
    "cep":"80050350",
    "numero":"80"
}

###
GET  {{url}}/cliente/2
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{url}}/cliente/
Authorization: Bearer {{token}}
Content-Type: application/json


###
POST  {{url}}/pedido/
Authorization: Bearer {{token}}
Content-Type: application/json 

{
    "cliente_id":5,
    "pedido_produtos":[
        {"produto_id":1,
        "pedido_produtos[0].quantidade_produto":20
        }
    ]
}



