@url = http://localhost:3000

###
GET {{url}}/categorias

###
POST {{url}}/usuario
Content-Type: application/json

{
    "nome":"Luiza",
    "email":"luh@teste.com",
    "senha":"12345"
}

###
# @name createLogin
POST {{url}}/login
Content-Type: application/json

{
    "email":"luh@teste.com",
    "senha":"12345"
}

###
@token = {{createLogin.response.body.token}}

###
@id = {{createLogin.response.body.authenticatedUser.id}}

###
GET {{url}}/usuario
Authorization: Bearer {{token}}

###
PUT {{url}}/usuario
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome":"Luiza Ferreira",
    "email":"luh@teste.com",
    "senha": "12345"
}

###
# @name createID
POST {{url}}/produto
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao":"Caixa de bombo",
    "quantidade_estoque":0,
    "valor":1000,
    "categoria_id": 2
}
###
POST {{url}}/produto
# @name createID
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao":"Caixa de bombo",
    "quantidade_estoque":0,
    "valor":1000,
    "categoria_id": 4
}
###
@id = {{createID.response.body.id}}

###
GET {{url}}/produto
Authorization: Bearer {{token}}

###
GET {{url}}/produto
?filtro[] =mercado
&&filtro[] =Celulares
&&filtro[] =teste
Authorization: Bearer {{token}}

###
PUT  {{url}}/produto/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao":"Caixa de bombo",
    "quantidade_estoque":0,
    "valor":1000,
    "categoria_id": 4
}
